export default {
  extends: [
    'stylelint-config-standard-scss',
  ],
  plugins: ['stylelint-order'],
  rules: {
    'selector-class-pattern': '^[a-z][a-zA-Z0-9]*(-[a-zA-Z0-9]+)*(__[a-zA-Z0-9]+(-[a-zA-Z0-9]+)*)*(--[a-zA-Z0-9]+(-[a-zA-Z0-9]+)*)*$|^[a-z][a-zA-Z0-9]*(-[a-zA-Z0-9]+)*$',
    'custom-property-pattern': null,
    'property-no-unknown': [
      true,
      {
        ignoreProperties: ['/^--/'],
      },
    ],
    'block-no-empty': true,
    'color-function-notation': 'modern',
    'unit-allowed-list': ['px', 'em', 'rem', '%', 'vh', 'vw', 'vmin', 'vmax', 'deg', 's', 'ms', 'fr'],
    'declaration-block-single-line-max-declarations': 3,
    'order/properties-order': [
      'position',
      'top',
      'right',
      'bottom',
      'left',
      'display',
      'flex-direction',
      'justify-content',
      'align-items',
      'width',
      'height',
      'margin',
      'padding',
      'border',
      'background',
      'color',
      'font-size',
      'font-family',
      'text-align',
      'line-height',
    ],
    'scss/dollar-variable-pattern': '^[a-z][a-zA-Z0-9]*(-[a-z][a-zA-Z0-9]*)*$',
    'scss/percent-placeholder-pattern': '^[a-z][a-zA-Z0-9]*(-[a-z][a-zA-Z0-9]*)*$',
  },
}
