services:
  app-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ..:/app
      - /app/node_modules
    env_file:
      - ../.env.development